application: liquid-champion-127202
version: 1
runtime: go
api_version: go1

handlers:
- url: /api.*
  script: _go_app

- url: /twitter/oauth.*
  script: _go_app

- url: /images/meicon.gif
  static_files: images/meicon.gif
  upload: images/meicon.gif
