application: japan-trip-university-backend
version: 1
runtime: go
api_version: go1

handlers:
- url: /api.*
  script: _go_app

- url: /images/meicon.gif
  static_files: static/images/meicon.gif
  upload: static/images/meicon.gif

